<?php
 $aik =  array (
  'sitename' => 'Butler 影院',
  'pcdomain' => 'http://movie.butlerwang.com',
  'title' => 'VIP影院-免VIP抢先观看最新好看的电影和电视剧',
  'keywords' => 'VIP影院,电视直播网站,零八影院快播,高清云影视,云点播,免费看视频,湖南卫视直播,80电影网,最新电影天堂免费在线观看',
  'description' => 'VIP影院,热剧快播,最好看的剧情片尽在﻿优奇艺影院,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播',
  'homelink' => '<a href="http://movie.butlerwang.com" target="_blank"><font color="red">【麦田淘客】</font></a>',
  'icp' => 'ICP备1882324992号',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传</br>若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢。',
  'tongji' => '',
  'changyan' => '',
  'youlian' => '<a target="blank" class="gobtn" href="http://movie.butlerwang.com">【麦田淘客】</a>	
<a target="blank" class="gobtn" href="">QQ群</a>',
  'jiekou1' => 'https://api.flvsp.com/?url=',
  'jiekou2' => 'https://api.47ks.com/webcloud/?v=',
  'jiekou3' => 'http://www.efunfilm.com/yunparse/index.php?url=',
  'jiekou4' => 'http://api.nepian.com/ckparse/?url=',
  'jiekou5' => 'http://aikan-tv.com/?url=',
  'jiekou6' => 'http://j.zz22x.com/jx/?url=',
  'jiekou7' => 'http://jiexi.071811.cc/jx2.php?url=',
  'jiekou8' => 'http://api.wlzhan.com/sudu/?url=',
  'jiekou9' => 'http://api.xfsub.com/index.php?url=',
  'jiekou10' => 'http://api.wlzhan.com/sudu/?url=',
  'admin_name' => 'admin',
  'admin_pass' => 'caeb49364a1217ca6792dae10a2728cc',
  'admin_email' => 'admin@admin.com',
  'logo_dh' => '<img src="images/logo.png">',
  'logo_ss' => '<img id="imgsrc" src="images/sologo.png">',
  'movie_ad' => '<a href="http://movie.butlerwang.com" target="_blank"><img src="images/ggzm.png" style="width:100%"></a>',
  'tv_ad' => '<a href="http://movie.butlerwang.com" target="_blank"><img src="images/ggzm.png" style="width:100%"></a>',
  'zongyi_ad' => '<a href="http://movie.butlerwang.com" target="_blank"><img src="images/ggzm.png" style="width:100%"></a>',
  'dongman_ad' => '<a href="http://movie.butlerwang.com" target="_blank"><img src="images/ggzm.png" style="width:100%"></a>',
  'bofang_ad' => '<img src="images/ggzm.png" style="width:100%"></a>',
  'jiazai_ad' => '<a href="http://movie.butlerwang.com" target="_blank"><img src="images/jiazai.png" width="100%"></a>',
  'dbts' => '【点击选择剧集才会播放哦！】',
  'zfb_ad' => '<img src="images/zfb.png">',
  'wx_ad' => '<img src="images/wx.png">',
  'cebian1_ad' => '<a class="style02" href="#" target="_blank"><strong>关注微信</strong><div class="article-wechats"> </br> <img src="images/qrcode.png"></div> </a>',
  'cebian2_ad' => '<a class="style02" href="http://movie.butlerwang.com" target="_blank"><strong>VIP影院</strong><h2>VIP影院-免VIP看视频</h2><p>VIP影院,热剧快播,最好看的剧情片尽在﻿VIP影院,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播。</p></a>',
  'cebian3_ad' => '<h3>广告赞助</h3>			
<div class="textwidget"><a href="http://movie.butlerwang.com"><img src="images/jianzhi.png" width="100%"></a>',
  'cebian4_ad' => '<a class="style01" href="http://t.cn/RpXLVVI"" target="_blank"><strong>网站特色</strong><h2>更好的视频主题</h2><p>1.扁平化、简洁风、多功能配置，优秀的电脑、平板、手机支持，响应式布局，不同设备不同展示效果...2.视频全自动采集，不需人工干预，懒人必备！</p></a></div>',
  'top2_ad' => '<a href="app.html">客户端</a>',
  'top_ad' => '<a href="http://movie.butlerwang.com/" target="_blank">优惠券</a>',
  'weixin_ad' => '<img src="images/qrcode.png">',
  'end_ad' => '<a href="http://movie.butlerwang.com/"><span><img src="images/gouwu.png"/>购物</span></a>',
  'hometopnotice' => '',
  'hometopright' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>